### PR TITLE
Extend exp_backoff stream with initial delay support

### PR DESCRIPTION
**Pull request by nothingelsematters7**

### CODE REVIEW

**Comment by safwank** [comment]
Thanks @nothingelsematters7. I'll take a look at it this weekend.

**Comment by safwank** [comment]
Merged. Thanks for the PR @nothingelsematters7!

**Comment by nothingelsematters7** [comment]
@safwank could you please create a new release for that feature to update our dependency to your repo with exact version?

**Comment by safwank** [comment]
@nothingelsematters7 I've released v0.6.1 that includes this PR.

**Pull request merged**
