### PR TITLE
Fix bug in expiry/3

### LINKED ISSUE #47: Bug: expiry/3 evaluates the expiry time at time of stream definition
`expiry/3` can lead to some very confusing behaviour if you don't immediately run the stream.

Here's an example test (that currently fails) to demonstrate:

```elixir
test "evaluates expiry at runtime of the stream, rather than execution time of expiry/3" do
  delay_stream =
    [50]
    |> Stream.cycle()
    |> expiry(75, 50)

  assert Enum.count(delay_stream, fn delay -> :timer.sleep(delay) end) == 2

  # If the expiry time is determined when `expiry/3` is executed, we will
  # already be past it (due to all the sleeps performed previously) and jump
  # out after the first run.
  assert Enum.count(delay_stream, fn delay -> :timer.sleep(delay) end) == 2
end
```

It would be much nicer if the stream could be re-used (kind of like a config value) instead.

### PR DESCRIPTION
**Pull request by jtrees**
This fix changes expiry/3 in such a way that the expiry time is
evaluated at runtime of the stream, rather than definition time.
This grants greater flexibility and enables setting up a configured
stream in advance (e.g. at compile time or in a gen_server init)
and passing the stream around for use in various places, at various
times.

See the added tests for an example.

Fixes #47

### CODE REVIEW

**Comment by safwank** [comment]
@jtrees Can you please fix the build issue before I merge the PR?

**Comment by jtrees** [comment]
Ah, yes. I'll check it out.

**Comment by jtrees** [comment]
Alright. Credo should be happy now.

**Review by safwank — APPROVED** [review]
LGTM.

**Pull request merged**
